import { ArrowUpRight, Plus, ShieldCheck } from 'lucide-react';
import { Avatar, DashboardShell, MiniStat } from '../components/DashboardShell';

export default function AdminDashboard() {
  const actions = <a href="/profile" className="hidden rounded-full border border-zinc-200 bg-white px-5 py-3 font-medium text-zinc-600 md:block">โปรไฟล์แอดมิน</a>;
  return <DashboardShell title="แดชบอร์ดผู้ดูแล" eyebrow="Admin Dashboard" role="admin" actions={actions}>
    <section className="mt-8 grid gap-7 xl:grid-cols-[1fr_420px]">
      <div className="min-w-0 space-y-7">
        <div className="hero-card rounded-[1.7rem] bg-[#6d5df6] p-8 text-white md:p-10"><p className="tracking-[.35em]">ศูนย์ควบคุม</p><h2 className="mt-5 max-w-3xl text-4xl font-medium leading-tight md:text-5xl">จัดการผู้เรียน คอร์ส และภาพรวมแพลตฟอร์มได้ในหน้าเดียว</h2><button id="seed-demo" className="mt-10 flex items-center gap-4 rounded-full bg-black px-7 py-4 font-medium" type="button">เพิ่มข้อมูลตัวอย่าง <span className="grid h-9 w-9 place-items-center rounded-full bg-white text-black"><Plus size={18} /></span></button></div>
        <div className="grid gap-5 md:grid-cols-3"><MiniStat label="สมาชิกทั้งหมด" value="0 คน" tone="purple" /><MiniStat label="แพ็กเกจฟรี" value="0 บัญชี" tone="pink" /><MiniStat label="ลิงก์รวม" value="0 ลิงก์" tone="blue" /></div>
        <section id="members" className="rounded-[1.7rem] bg-white p-6"><div className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-semibold">รายชื่อสมาชิก</h2><p className="text-zinc-400">เลือกสมาชิกเพื่อแก้ไขข้อมูลด้านขวา</p></div><div className="grid grid-cols-3 gap-3 text-center"><Stat id="total-members" label="สมาชิก" /><Stat id="free-members" label="ฟรี" /><Stat id="total-links" label="ลิงก์" /></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="text-zinc-400"><tr><th className="py-3">ผู้เรียน</th><th>อีเมล</th><th>แพ็กเกจ</th><th>สร้างเมื่อ</th><th></th></tr></thead><tbody id="member-rows" className="divide-y divide-zinc-100"></tbody></table></div></section>
        <section id="reports" className="grid gap-5 md:grid-cols-3"><Report title="คอร์สใช้งาน" value="24" /><Report title="บทเรียนใหม่" value="8" /><Report title="คำขอซัพพอร์ต" value="3" /></section>
      </div>
      <aside className="space-y-7"><section className="rounded-[1.7rem] bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-semibold">ภาพรวมระบบ</h2><ShieldCheck className="text-[#6d5df6]" /></div><div className="mx-auto mt-7 grid h-44 w-44 place-items-center rounded-full border-[10px] border-[#eee7ff]"><Avatar seed={9} className="h-28 w-28 text-6xl" /></div><h3 className="mt-5 text-center text-2xl font-semibold">สวัสดี ผู้ดูแลระบบ 🔥</h3><p className="text-center text-zinc-400">ตรวจสอบคุณภาพการเรียนและสมาชิกประจำวัน</p><div className="mt-8 flex h-52 items-end justify-around rounded-[1.5rem] bg-[#f5f6fb] px-6 py-8"><Bar h="45%" /><Bar h="70%" active /><Bar h="40%" /><Bar h="92%" active /><Bar h="52%" /></div></section><section id="settings" className="rounded-[1.7rem] bg-white p-7"><h2 className="text-2xl font-semibold">แก้ไขข้อมูลสมาชิก</h2><p className="mb-6 text-zinc-400">ข้อมูลจะถูกบันทึกผ่าน Supabase หรือ localStorage สำรอง</p><form id="admin-edit" className="grid gap-4"><input name="selected" type="hidden" /><Field name="username" label="ชื่อผู้ใช้" required /><Field name="email" label="อีเมล" type="email" required /><label className="space-y-2 text-sm font-medium text-zinc-500">แพ็กเกจ<select name="plan" className="w-full rounded-2xl border border-zinc-200 bg-[#f7f8fd] px-4 py-3 outline-none focus:border-[#6d5df6]"><option>ฟรี</option><option>โปร</option><option>แอดวานซ์</option></select></label><Field name="displayName" label="ชื่อแสดงผล" /><label className="space-y-2 text-sm font-medium text-zinc-500">ประวัติย่อ<textarea name="bio" rows={4} className="w-full rounded-2xl border border-zinc-200 bg-[#f7f8fd] px-4 py-3 outline-none focus:border-[#6d5df6]" /></label><button className="rounded-2xl bg-[#6d5df6] px-6 py-4 font-semibold text-white shadow-xl shadow-indigo-200" type="submit">บันทึกสมาชิก</button></form></section></aside>
    </section>
  </DashboardShell>;
}

function Field({ label, name, type = 'text', required }: { label: string; name: string; type?: string; required?: boolean }) { return <label className="space-y-2 text-sm font-medium text-zinc-500">{label}<input name={name} type={type} required={required} className="w-full rounded-2xl border border-zinc-200 bg-[#f7f8fd] px-4 py-3 outline-none focus:border-[#6d5df6]" /></label>; }
function Stat({ id, label }: { id: string; label: string }) { return <div className="rounded-2xl bg-[#f5f6fb] px-4 py-2"><p id={id} className="text-xl font-semibold">0</p><p className="text-xs text-zinc-400">{label}</p></div>; }
function Report({ title, value }: { title: string; value: string }) { return <article className="rounded-[1.5rem] bg-white p-6"><p className="text-zinc-400">{title}</p><h3 className="mt-4 text-4xl font-semibold">{value}</h3></article>; }
function Bar({ h, active }: { h: string; active?: boolean }) { return <span className={`w-12 rounded-lg ${active ? 'bg-[#6d5df6]' : 'bg-[#cbc5ff]'}`} style={{ height: h }} />; }
