import { ArrowUpRight, Heart, Plus } from 'lucide-react';
import { Avatar, DashboardShell, MiniStat } from '../components/DashboardShell';

const courses = [
  ['ฟรอนต์เอนด์', 'คู่มือเริ่มต้นสู่การเป็นนักพัฒนา Front-End มืออาชีพ', 'ลีโอนาร์โด แซมซูล', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80'],
  ['UI/UX ดีไซน์', 'ปรับประสบการณ์ผู้ใช้ด้วยงานออกแบบที่ดีที่สุด', 'บายู ซัลโต', 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=800&q=80'],
  ['แบรนดิ้ง', 'รีเฟรชภาพลักษณ์บริษัทให้ทันสมัยและน่าจดจำ', 'พัดหาง สาทริโอ', 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80'],
];

export default function MemberDashboard() {
  return <DashboardShell title="แดชบอร์ดผู้เรียน" eyebrow="คอร์สออนไลน์" role="member">
    <section className="mt-8 grid gap-7 xl:grid-cols-[1fr_420px]">
      <div className="min-w-0 space-y-7">
        <div className="hero-card rounded-[1.7rem] bg-[#6d5df6] p-8 text-white md:p-10"><p className="tracking-[.35em]">คอร์สออนไลน์</p><h2 className="mt-5 max-w-3xl text-4xl font-medium leading-tight md:text-5xl">ลับทักษะของคุณด้วยคอร์สออนไลน์ระดับมืออาชีพ</h2><button className="mt-10 flex items-center gap-4 rounded-full bg-black px-7 py-4 font-medium">เริ่มเรียน <span className="grid h-9 w-9 place-items-center rounded-full bg-white text-black"><ArrowUpRight size={18} /></span></button></div>
        <div className="grid gap-5 md:grid-cols-3"><MiniStat label="UI/UX ดีไซน์" value="ดูแล้ว 2/8" /><MiniStat label="แบรนดิ้ง" value="ดูแล้ว 3/8" tone="pink" /><MiniStat label="ฟรอนต์เอนด์" value="ดูแล้ว 6/12" tone="blue" /></div>
        <section id="lessons" className="space-y-5"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">เรียนต่อ</h2><div className="flex gap-3"><button className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#6d5df6]">‹</button><button className="grid h-10 w-10 place-items-center rounded-full bg-[#6d5df6] text-white">›</button></div></div><div className="grid gap-6 lg:grid-cols-3">{courses.map((course, index) => <article key={course[1]} className="rounded-[1.7rem] bg-white p-5"><div className="relative h-40 overflow-hidden rounded-[1.4rem]"><img src={course[3]} alt="" className="h-full w-full object-cover" /><button className="absolute right-3 top-3 grid h-10 w-10 place-items-center rounded-full bg-black/35 text-white"><Heart size={20} /></button></div><p className="mt-4 inline-flex rounded-full bg-[#edf7ff] px-3 py-1 text-sm font-semibold text-[#45b6e8]">{course[0]}</p><h3 className="mt-3 min-h-16 text-xl font-medium leading-tight">{course[1]}</h3><div className="mt-5 h-1 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-[#6d5df6]" style={{ width: `${60 + index * 10}%` }} /></div><div className="mt-5 flex items-center gap-3"><Avatar seed={index + 2} /><div><p className="font-medium">{course[2]}</p><p className="text-sm text-zinc-400">เมนเทอร์</p></div></div></article>)}</div></section>
        <section id="tasks" className="rounded-[1.7rem] bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">บทเรียนของคุณ</h2><a className="font-medium text-[#6d5df6]" href="#">ดูทั้งหมด</a></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="text-zinc-400"><tr><th className="py-3">เมนเทอร์</th><th>ประเภท</th><th>รายละเอียด</th><th>การทำงาน</th></tr></thead><tbody><tr className="border-t"><td className="py-4"><div className="flex items-center gap-3"><Avatar seed={5} />พัดหาง สาทริโอ</div></td><td><span className="rounded-full bg-[#eee7ff] px-3 py-1 text-[#6d5df6]">UI/UX ดีไซน์</span></td><td>ทำความเข้าใจ UI/UX Design</td><td><button className="grid h-9 w-9 place-items-center rounded-full border text-[#6d5df6]">↗</button></td></tr></tbody></table></div></section>
      </div>
      <RightPanel />
        <form id="profile-settings" className="sr-only"><input name="username" /><input name="email" type="email" /><input name="displayName" /><textarea name="bio" /><input name="website" /><input name="discord" /><input name="backgroundImage" /></form><input id="background-upload" name="backgroundImage" type="file" accept="image/*" className="sr-only" /><div id="background-preview" className="hidden" /><button id="remove-background" type="button" className="hidden">ลบรูปพื้นหลัง</button><span id="profile-slug" className="sr-only">member</span><span id="links-count" className="sr-only">0</span><div id="inbox" className="sr-only" /><div id="badges" className="sr-only" /><div id="widgets" className="sr-only" /><div id="songs" className="sr-only" /><div id="security" className="sr-only" /><div id="appearance" className="sr-only" /><div id="links" className="sr-only" />
    </section>
  </DashboardShell>;
}

function RightPanel() {
  return <aside className="space-y-7"><section className="rounded-[1.7rem] bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-semibold">สถิติ</h2><span className="text-2xl text-zinc-400">⋮</span></div><div className="mx-auto mt-7 grid h-44 w-44 place-items-center rounded-full border-[10px] border-[#eee7ff]"><Avatar seed={4} className="h-28 w-28 text-6xl" /></div><h3 className="mt-5 text-center text-2xl font-semibold">อรุณสวัสดิ์ เจสัน 🔥</h3><p className="text-center text-zinc-400">เรียนต่อเพื่อไปให้ถึงเป้าหมายของคุณ!</p><div className="mt-8 flex h-52 items-end justify-around rounded-[1.5rem] bg-[#f5f6fb] px-6 py-8"><Bar h="38%" /><Bar h="62%" active /><Bar h="38%" /><Bar h="88%" active /><Bar h="34%" /></div></section><section id="group" className="rounded-[1.7rem] bg-white p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-semibold">เมนเทอร์ของคุณ</h2><button className="grid h-10 w-10 place-items-center rounded-full border text-[#6d5df6]"><Plus size={20} /></button></div>{['พัดหาง สาทริโอ', 'ซากีร์ ฮอริซอนทัล', 'ลีโอนาร์โด แซมซูล'].map((name, index) => <div key={name} className="mt-6 flex items-center gap-4 border-b border-dashed pb-5 last:border-0"><Avatar seed={index + 5} /><div className="mr-auto"><p className="font-medium">{name}</p><p className="text-sm text-zinc-400">เมนเทอร์</p></div><button className="rounded-full border border-[#ddd7ff] px-5 py-2 font-medium text-[#6d5df6]">ติดตาม</button></div>)}<button className="mt-3 w-full rounded-full bg-[#eee7ff] py-4 font-medium text-[#6d5df6]">ดูทั้งหมด</button></section></aside>;
}
function Bar({ h, active }: { h: string; active?: boolean }) { return <span className={`w-12 rounded-lg ${active ? 'bg-[#6d5df6]' : 'bg-[#cbc5ff]'}`} style={{ height: h }} />; }
